# Generated by Django 5.0.1 on 2024-01-21 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='friend', max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('assignement', models.CharField(max_length=30, null=True)),
                ('assignement_description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='task', max_length=30)),
                ('description', models.CharField(blank=True, default=models.CharField(blank=True, default='task', max_length=30), max_length=255, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('location', models.CharField(choices=[('O', 'Other'), ('H', 'Home'), ('Uv', 'University')], default='H', max_length=40, null=True)),
                ('subject', models.CharField(choices=[('C', 'C_Programming'), ('Py', 'Python'), ('Dj', 'Django'), ('Opt', 'Optimization'), ('Net', 'Networking'), ('Algo', 'Algorythms'), ('Data_Structs', 'Data_Structures'), ('Linux', 'Linux'), ('X86', 'Computer_Architecture')], default='Py', max_length=30, null=True)),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.member')),
            ],
        ),
    ]
