# Generated by Django 5.0.1 on 2024-01-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_left',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(choices=[('H', 'Home'), ('O', 'Other'), ('Uv', 'University')], default='H', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('Py', 'Python'), ('Dj', 'Django'), ('Linux', 'Linux'), ('Net', 'Networking'), ('C', 'C_Programming'), ('Algo', 'Algorythms'), ('Opt', 'Optimization'), ('Crypto', 'Cryptography'), ('X86', 'Computer_Architecture'), ('Data_Structs', 'Data_Structures')], default='Py', max_length=30, null=True),
        ),
    ]
