# Generated by Django 5.0.1 on 2024-01-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_time_left_alter_task_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='User', max_length=50, unique=True)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('salt', models.CharField(default='4321', max_length=50)),
                ('tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
