# Generated by Django 5.0.1 on 2024-01-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.member'),
        ),
    ]
