# Generated by Django 5.0.1 on 2024-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
