# Generated by Django 5.0.1 on 2024-01-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_custom_user_password_alter_custom_user_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='tasks',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='tasks',
            field=models.ManyToManyField(null=True, related_name='users', to='tasks.task'),
        ),
    ]
