# Generated by Django 5.0.1 on 2024-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_custom_user_tasks_custom_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(choices=[('Home', 'Home'), ('Other', 'Other'), ('University', 'University')], default='H', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Linux', 'Linux'), ('Networking', 'Networking'), ('C_Programming', 'C_Programming'), ('Algorythms', 'Algorythms'), ('Optimization', 'Optimization'), ('Cryptography', 'Cryptography'), ('Computer_Architecture', 'Computer_Architecture'), ('Data_Structures', 'Data_Structures')], default='Py', max_length=30, null=True),
        ),
    ]
